(function(g){var window=this;'use strict';var sgb=function(a,b,c){var d;g.J(function(e){switch(e.j){case 1:var f=b;a.Y.L("web_player_pt_tt")?(f=g.Jr(f).exp||"",f=f.includes("xpv")||f.includes("xpe")):f=!1;if(!f){e.Ea(2);break}if(a.videoData.Pw){e.Ea(3);break}g.wa(e,4);return g.G(e,a.D.promise,6);case 6:g.xa(e,3);break;case 4:return g.ya(e),e.return();case 3:d={potc:"1",pot:a.videoData.Pw},b=g.Kr(b,d);case 2:a.j=g.ds(b,c),g.va(e)}})},A3=function(a){a.isActive()||a.start()},tgb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},
ugb=function(a){return g.gQ(a)||a.L("web_enable_caption_language_preference_stickiness")},vgb=function(a,b){var c=new g.xQ;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},wgb=function(a,b){var c,d,e;
return g.J(function(f){if(f.j==1)return c=a+"|"+b,g.G(f,g.Pu(),2);if(f.j!=3){d=f.B;if(!d)throw g.bu("gct");return g.G(f,g.PQ(d),3)}e=f.B;return f.return(e.get("captions",c))})},xgb=function(a,b,c){wgb(a,b).then(function(d){d&&c(d.trackData,new g.xQ(d.metadata))})},Agb=function(a){if(!ygb.test(a))throw Error("'"+a+"' is not a valid hex color");
a.length==4&&(a=a.replace(zgb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Bgb=function(){var a=void 0;
a=a===void 0?{}:a;var b="suggest_correction"in g.ddb?g.ddb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={DG:c.DG};c.DG=d;var e=function(f){return function(){return String(a[f.DG])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.DG+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.DG,"gi"),e)}return b},Cgb=function(){return g.mt("yt-player-caption-display-settings")},B3=function(){this.segments=[]},Dgb=function(a,b){var c=g.fc(a.segments,b);
c>=0||c<0&&(-c-1)%2===1||(c=-c-1,c>0&&b-a.segments[c-1]===1&&c<a.segments.length&&a.segments[c]-b===1?(g.Xb(a.segments,c),g.Xb(a.segments,c-1)):c>0&&b-a.segments[c-1]===1?a.segments[c-1]=b:c<a.segments.length&&a.segments[c]-b===1?a.segments[c]=b:(g.dc(a.segments,c,0,b),g.dc(a.segments,c+1,0,b)))},Egb=function(a,b,c,d,e,f){g.O.call(this);
this.policy=a;this.player=b;this.oa=c;this.Z=d;this.G=e;this.W=f;this.D=new B3;this.K=-1;this.C=this.B=this.j=null;this.qa=0;this.N=new g.Ep(this.K_,1E3,this);this.events=new g.kG(this);g.P(this,this.N);g.P(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.aC);this.aC();this.K_()},Fgb=function(a){return a.j&&a.j.Tf?a.j.Tf+a.player.Bc()<a.player.getCurrentTime():!1},Ggb=function(a,b){if(a.policy.Dm&&a.player.Cu()){var c=g.RN(b,a.policy,{});
c.set("pot",a.player.Cu());c=c.ye()}else c=g.RN(b,a.policy,{}).ye();var d={format:"RAW",withCredentials:!0};if(a.policy.Oa){d.method="POST";var e=b.D;e&&Object.keys(e).length>0?d.postBody=g.PB(e,g.bM):d.postBody=(0,g.cU)([120,0])}a.G&&(d.responseType="arraybuffer");var f=++a.qa,h=(0,g.hu)();a.C=g.hs(c,d,3,100).then(function(l){if(a.policy.BG&&f%100===1){var m=(0,g.hu)();a.player.ma("caprsp",{rn:f,ms:m-h,kb:(l.xhr.responseText.length/1024).toFixed()})}a:{l=l.xhr;a.Ja();if(a.B){var n=!(a.G?l.response:
l.responseText)||l.status>=400;if(m=g.sFa(l)){l=g.RN(a.B,a.policy,{});a.B.Lk(l,m);Ggb(a,a.B);break a}n?a.player.ma("capfail",{status:l.status}):(a.player.Mh().pg("fcb_r"),m=a.B.ib[0].Ma,a.Z!=null&&a.K!==m&&(n=a.B.ib[0],a.G?a.Z(l.response,(n.startTime+a.player.Bc())*1E3):a.Z(l.responseText,(n.startTime+a.player.Bc())*1E3),a.K=m))}a.B=null;a.C=null}}).il(function(l){a.B=null;
a.C=null;var m;a.player.ma("capfail",{rn:f,status:(m=l.xhr)==null?void 0:m.status})});
a.B=b;Dgb(a.D,a.B.ib[0].Ma)},C3=function(a,b){g.kY.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.K=!1;this.N=g.fE(this.J.U())&&!this.j.isManifestless},Igb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.G0a(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.ueb.get(e);q==null&&(q=Hgb[e]||Hgb[e.replace(/-/g,"_")],g.ueb.set(e,q));h=q||h}c.push(new g.xQ({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
Jgb=function(a,b){return b!=null&&b in a.j.j?a.j.j[b]:null},Kgb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.G0a(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},D3=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Ve);a.params.Ve&&Object.assign(r,a.params.Ve);Object.assign(r,c.Ve);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Ve=r;var t=q.Xi===1,u=[{I:"span",S:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],y,A,C;(l=l.bb("caption_edit_on_hover")&&((y=n.getVideoData().getPlayerResponse())==null?void 0:(A=y.captions)==null?void 0:(C=A.playerCaptionsTracklistRenderer)==null?void 0:C.openTranscriptCommand))&&
u.unshift({I:"button",S:"caption-edit",X:{tabindex:"0","aria-label":Bgb()},V:[{I:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.S.call(this,{I:"div",S:"caption-window",X:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:u});var F=
this;this.K=[];this.Fa=!1;this.B=a;this.Ia=this.Ka=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=f*.96;this.maxHeight=h*.96;this.j=q;this.zc=c;this.qa=b;this.D=this.Da("captions-text");this.Rb=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Ua=dhb(d,e,f,h);this.uc=m;l&&(this.G=this.Da("caption-edit"),this.T(this.G,"click",function(){F.uc()}));
this.type=0;this.Wa=this.Ua*ehb(r);this.Eb=p;a=new g.LX(this.element,!0);g.P(this,a);a.subscribe("dragstart",this.l5,this);a.subscribe("dragmove",this.k5,this);a.subscribe("dragend",this.j5,this);this.eb=this.Ya=this.sb=this.qb=0;a="";this.j.windowOpacity&&(a=Agb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:this.j.isVisible===!1?"none":"","text-align":fhb[this.j.textAlign]};this.Rb&&(b["border-radius"]=a?this.Wa/8+"px":"");(this.C=
this.B.params.Xi===2||this.B.params.Xi===3)&&ghb(this,this.element);g.Fm(this.element,b);if(p){var H;(H=this.element.parentElement)==null||H.style.setProperty("--caption-window-color",a)}switch(this.j.Rm){case 0:case 1:case 2:g.Mp(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Mp(this.element,"ytp-caption-window-bottom")}},ghb=function(a,b){var c="vertical-rl";
a.j.TU===1&&(c="vertical-lr");g.Hm&&(c=c==="vertical-lr"?"tb-lr":"tb-rl");g.Fm(b,"-o-writing-mode",c);g.Fm(b,"-webkit-writing-mode",c);g.Fm(b,"writing-mode",c);g.Fm(b,"text-orientation","upright");g.Mp(b,"ytp-vertical-caption");a.B.params.Xi===3&&(g.Fm(b,"text-orientation",""),g.Fm(b,"transform","rotate(180deg)"))},ehb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(a.offset===0||a.offset===2)b*=.8;return b},hhb=function(a,b){var c={},d=b.background?b.background:a.j.Ve.background;
if(b.backgroundOpacity!=null||b.background){var e=b.backgroundOpacity!=null?b.backgroundOpacity:a.j.Ve.backgroundOpacity;d=Agb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Rb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Wa/8+"px")}if(b.fontSizeIncrement!=null||b.offset!=null)c["font-size"]=a.Ua*ehb(b)+"px";d=1;e=b.color||a.j.Ve.color;if(b.color||b.textOpacity!=null)e=Agb(e),d=b.textOpacity==null?a.j.Ve.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;f===0&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.mP&&(h=e=b.mP);var l=a.Ua/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=window.devicePixelRatio>=2?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;p<5;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.ws()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;e==null&&(e=a.j.Ve.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}b.fontFamily===7&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]=
"underline");b.C$&&(c.visibility="hidden");b.TZ===1&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.jQ||g.$t,a.B.params.Xi===3?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(b.Cp===1||b.Cp===2||b.Cp===3||b.Cp===4||b.Cp===5)if(g.jQ)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Cp){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},E3=function(a){a=a.split("px");
return a.length>0?(a=Number(a[0]))?a:0:0},ihb=function(a){a.N=g.qh("SPAN");
g.Fm(a.N,{display:"block"});g.Mp(a.N,"caption-visual-line");a.D.appendChild(a.N)},jhb=function(a,b){var c=g.qh("SPAN");
g.Fm(c,{display:"inline-block","white-space":"pre-wrap"});g.Fm(c,hhb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.Fm(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Fm(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},khb=function(a,b,c){a.Fa=a.Fa||!!c;
var d={};Object.assign(d,a.j.Ve);Object.assign(d,c||b.j);Object.assign(d,a.zc.Ve);(c=!a.N)&&ihb(a);for(var e=a.Ka&&a.Ia&&g.Xg(d,a.Ia)?a.Ka:jhb(a,d),f=typeof b.text==="string",h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=l>0||!b.append,n=h[l];m&&!c?(ihb(a),e=jhb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.rh(n):n),f||n.tagName!=="RUBY"||n.childElementCount!==4||g.jQ||!g.Im(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.Im(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.mh?g.Fm(e,m,"1em"):g.Fm(e,m,"0.5em")))}a.Ia=d;a.Ka=e;a.K.push(b)},dhb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>c*1.3&&(a=480),e=c/a*16);return e},mhb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new lhb(this);this.G=new lhb(this);this.j=[];this.clear()},ohb=function(a,b,c){if(a===255&&b===255||!a&&!b)return{hx:a,
Ut:b,result:0};a=nhb[a];b=nhb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.ze()&&c.Ut===d;if(d)return{hx:a,Ut:b,result:1}}else if(b&128&&1<=a&&a<=31)return{hx:a,Ut:b,result:2};return{hx:a,Ut:b,result:3}},qhb=function(a,b,c,d){b===255&&c===255||!b&&!c?(++a.C===45&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,phb(a.D,b,c,d))},rhb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return h===0?e.order-f.order:h});
for(var c=g.w(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,d.type===0?qhb(a,d.YX,d.ZX,b):d.type===1&&a.B&496&&phb(a.G,d.YX,d.ZX,b);a.j.length=0},F3=function(){this.type=0},G3=function(){this.state=this.Ut=this.hx=0},shb=function(){this.timestamp=this.j=0},H3=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new F3;for(a=this.C=0;a<=15;a++){this.B[a]=[];for(var b=0;b<=32;b++)this.B[a][b]=new shb}},I3=function(a,b){if(a.style.type===3){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;m<=15;++m){for(var n=!1,p=d?d:1;p<=32;++p){var q=a.B[m][p];
if(q.j!==0){c===0&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((q.j===0||p===32)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;h<=15;++h)for(l="",m=1;m<=32;++m)if(p=a.B[h][m],q=p.j,q!==0&&(c===0&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),m===32||q===0)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},xhb=function(a,b){switch(a){case 0:return thb[(b&127)-32];
case 1:return uhb[b&15];case 2:return vhb[b&31];case 3:return whb[b&31]}return 0},J3=function(a){return a.B[a.row][a.col]},K3=function(a,b,c){b>=2&&a.col>1&&(--a.col,J3(a).j=0);
var d=J3(a);d.timestamp=a.D.time+0;d.j=xhb(b,c);a.col<32&&a.col++},yhb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;f<=32;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},L3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;e<=32;e++)a.B[b+d][e].reset()},zhb=function(a){a.row=a.j>0?a.j:1;
a.col=1;L3(a,0,15)},Ahb=function(a){this.C=a;
this.G=0;this.style=new F3;this.K=new H3(this.C);this.N=new H3(this.C);this.text=new H3(this.C);this.B=this.K;this.D=this.N;this.j=this.B},Bhb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:a.style.get()===4&&d.j>0||(I3(d,c),zhb(a.B),zhb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(I3(d,c),L3(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Chb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},Dhb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},lhb=function(a){this.j=a;
this.G=0;this.C=new Ahb(this.j);this.K=new Ahb(this.j);this.B=new G3;this.D=this.C},phb=function(a,b,c,d){a.B.update();
b=ohb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.hx;c=b.Ut;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&K3(a,0,b),c&96&&K3(a,0,c),b!==0&&c!==0&&a.style.type===3&&I3(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.hx=e,b.Ut=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(b.style.type===4?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(b.style.type!==4?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?((c&14)>>1)*4:0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;yhb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,f>0&&(b+=f,e-=f)):(f=f+e-h,f>0&&(e-=f));L3(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:K3(b.j,0,32);break a;case 48:c===57?(d=b.j,J3(d).j=0,d.col<32&&d.col++):K3(b.j,1,c&15)}break;case 2:c&32&&K3(b.j,2,c&31);break;case 3:c&32&&K3(b.j,3,c&31);break;case 4:case 5:if(32<=c&&c<=47)switch(c){case 32:Chb(b);
break;case 33:d=b.j;d.col>1&&(--d.col,J3(d).j=0);break;case 36:d=b.j;b=J3(d);for(a=0;a<=15;a++)for(c=0;c<=32;c++)if(d.B[a][c]===b){for(;c<=32;c++)d.B[a][c].reset();break}break;case 37:Bhb(b,2,d);break;case 38:Bhb(b,3,d);break;case 39:Bhb(b,4,d);break;case 40:K3(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);zhb(d);Dhb(b);break;case 43:Dhb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:I3(a,
d)}L3(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(a.row<15){++a.row;a.col=1;break b}break;case 3:}a.j<2&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;I3(a,d);yhb(a,b,b+1,a.j-1);L3(a,a.row,1)}break;case 46:L3(b.D,0,15);break;case 47:I3(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,Chb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,(d.col+=c&3)>32&&(d.col=32)}}},Ehb=function(){},M3=function(a,b,c,d,e,f,h){f=f===void 0?!1:f;
h=h===void 0?null:h;g.KE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},Ghb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(m.jg===1){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Fhb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new M3(a,b,e,c,l,d,m)}switch(m.jg){case 9:case 10:m.Cp=1;break;case 11:m.Cp=2;break;case 12:m.Cp=3;break;case 13:m.Cp=4;break;case 14:m.Cp=5}return new M3(a,b,e,c,l.textContent||"",d,m)},Fhb=function(a,b,c,d,e){var f=g.ws(),h=
f?g.qh("DIV"):g.qh("RUBY"),l=g.qh("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.qh("DIV"):g.qh("RP");a.textContent=b;h.appendChild(a);b=f?g.qh("DIV"):g.qh("RT");b.textContent=c;h.appendChild(b);c=e.jg;if(c===10||c===11||c===12||c===13||c===14)if(g.Fm(b,"text-emphasis-style","filled circle"),g.Fm(b,"text-emphasis-color","currentcolor"),g.Fm(b,"webkit-text-emphasis","filled circle"),e.jg===11||e.jg===13)g.Fm(b,"webkit-text-emphasis-position","under left"),g.Fm(b,"text-emphasis-position","under left");c=!0;if(e.jg===4||e.jg===7||e.jg===12||
e.jg===14)g.Fm(h,"ruby-position","over"),g.Fm(h,"-webkit-ruby-position","before");else if(e.jg===5||e.jg===6||e.jg===11||e.jg===13)g.Fm(h,"ruby-position","under"),g.Fm(h,"-webkit-ruby-position","after"),c=!1;e=f?g.qh("DIV"):g.qh("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Fm(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Fm(f,"display","none"),f=f.nextElementSibling,g.Fm(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Fm(h.lastElementChild,"display","none"),d?(g.Fm(h,"padding-top","0.6em"),g.Fm(f,"top","0")):(g.Fm(h,"padding-bottom","0.6em"),g.Fm(f,"bottom","0")));return h},N3=function(){g.O.apply(this,arguments)},O3=function(a,b,c,d,e){g.KE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Hhb=function(a){var b="_"+P3++;
return new O3(0,0x8000000000000,0,b,a)},Q3=function(a){N3.call(this);
this.C=a;this.pens={};this.N={};this.Z={};this.D="_"+P3++;this.K={};this.B=this.j=null;this.G=!0},R3=function(a,b){a=a.getAttribute(b);
if(a!=null)return Number(a)},S3=function(a,b){a=a.getAttribute(b);
if(a!=null)return a==="1"},T3=function(a,b){a=R3(a,b);
return a!==void 0?a:null},V3=function(a,b){a=a.getAttribute(b);
if(a!=null)return U3.test(a),a},Ihb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=T3(b,"mh");a!=null&&(c.PB=a);a=T3(b,"ju");a!=null&&(c.textAlign=a);a=T3(b,"pd");a!=null&&(c.Xi=a);a=T3(b,"sd");a!=null&&(c.TU=a);a=V3(b,"wfc");a!=null&&(c.windowColor=a);b=R3(b,"wfo");b!==void 0&&(c.windowOpacity=b/255);return c},Jhb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=T3(b,"ap");a!=null&&(c.Rm=a);a=R3(b,"cc");a!=null&&(c.Xt=a);a=R3(b,"ah");a!=null&&(c.Pk=a);a=R3(b,"rc");a!=null&&(c.Us=a);b=R3(b,"av");b!=null&&(c.Fp=b);return c},Khb=function(a,b,c,d){var e={};
Object.assign(e,Jhb(a,b));Object.assign(e,Ihb(a,b));d?g.Xg(e,a.C)?(d=a.D,e=a.C):d="_"+P3++:d=b.getAttribute("id")||"_"+P3++;a=R3(b,"t")+c;b=R3(b,"d")||0x8000000000000;if(e.Xi===2||e.Xi===3)c=e.Us,e.Us=e.Xt,e.Xt=c;return new O3(a,b,0,d,e)},W3=function(a){N3.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},X3=function(a){a=g.Bg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Lhb=function(a,b,c,d,e){d===0&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;a!==void 0&&(f.Us=a);b=b.ccColCount;b!==void 0&&(f.Xt=b);if(f.Xi===2||f.Xi===3)b=f.Us,f.Us=f.Xt,f.Xt=b;return new O3(c,d,0,e,f)},Y3=function(a,b,c,d){g.kY.call(this,a);
this.videoData=b;this.audioTrack=c;this.Sa=d;this.G=b.Mw},Z3=function(a,b,c,d,e,f,h,l,m,n){D3.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},$3=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.B=[];this.j=new DataView(this.trackData)},a4=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},b4=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},c4=function(a,b){N3.call(this);
this.B=a;this.C=b;this.track=this.C.languageName==="CC3"?4:0;this.j=new mhb;this.j.B=1<<this.track},Nhb=function(a){if(typeof a==="string")return!1;
a=new $3(a,8,0);return Mhb(a)},Mhb=function(a){if(!(a.byteOffset<a.j.byteLength)||b4(a)!==1380139777)return!1;
a.version=a4(a);if(a.version>1)return!1;a4(a);a4(a);a4(a);return!0},d4=function(a,b,c,d,e,f,h,l,m,n){D3.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Aa=[];this.oa=this.W=this.Oa=0;this.Ca=NaN;this.Hb=0;this.Ub=null;this.Ta=new g.Ep(this.Dca,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.LX(this.element,!0),g.P(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.Mp(this.element,"ytp-caption-window-rollup");g.P(this,this.Ta);g.Fm(this.element,"overflow","hidden")},Ohb=function(a,b){if(!b)return"";
a.C&&a.B.params.TU!==1&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},Phb=function(a){a.Aa=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Us,c=0,d=0,e=a.Aa.length-1;c<b&&e>-1;){var f=a.Aa[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.W=d;b=Math;c=b.max;isNaN(a.Ca)&&((d=a.j.Xt)?(e=g.qh("SPAN"),g.xh(e,"\u2013".repeat(d)),g.Fm(e,hhb(a,a.j.Ve)),a.D.appendChild(e),a.Ca=e.offsetWidth,a.D.removeChild(e)):a.Ca=0);d=a.D;a.oa=c.call(b,a.Ca,a.Hb,(a.C?d.offsetHeight:d.offsetWidth)+1)},Qhb=function(a,b){Phb(a);
var c=a.Aa.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.W-c;if(c!==a.Oa){var d=c>0&&a.Oa===0,e=c<a.Oa;b||isNaN(c)||d||!e||(g.Mp(a.element,"ytp-rollup-mode"),g.Fp(a.Ta));g.Fm(a.D,"transform",Ohb(a,c));a.Oa=c}Phb(a)},e4=function(){N3.call(this)},Rhb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(p.nodeType===3)p=new M3(b,c,d,e.id,p.nodeValue,f||n>0,g.Sg(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Rhb(a,b,c,d,e,!0,p,q,m)}}},Shb=function(a){var b=a.split(":");
a=0;b=g.w(b);for(var c=b.next();!c.done;c=b.next())a=a*60+Number(c.value);return a*1E3},Thb=function(a,b,c,d){d=Object.assign({PB:0},d);
return new O3(a,b,c,"_"+P3++,d)},f4=function(a,b){g.O.call(this);
this.J=a;this.Y=b;this.j=null;this.B=this.J.UA();this.logger=new g.PT("caps")},Uhb=function(a){if(typeof a==="string"||Nhb(a))return a;
var b=new DataView(a);if(b.byteLength<=8||b.getUint32(4)!==1718909296)return"";b=g.VM(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.tB(a)},Whb=function(a,b,c){if(typeof b==="string"||Nhb(b))return[{trackData:b,
NU:c}];var d=new DataView(b);if(d.byteLength<=8||d.getUint32(4)!==1718909296)return[];var e=g.rEa(d);if(a.B&&e){var f=g.jEa(e),h=g.kEa(e);e=e.vj;f&&e&&a.B.JI(e,f,h)}a=g.dN(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.tB(e),f.push({trackData:e,NU:c+h*1E3});Vhb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},Vhb=function(a,b,c){var d=g.VM(a,0,1836476516),e=9E4;
d&&(e=g.WM(d)||9E4);d=0;for(var f=g.dN(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.VM(a,l.dataOffset,1953653094))&&(l=g.VM(a,l.dataOffset,1952867444))&&(l=g.bN(l)/e*1E3,h===0&&(d=l),b[h].NU=l-d+c||c*h*1E3)}},Xhb=function(a,b,c,d,e){if(!Nhb(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new c4(e,b));return a.j.kp(c,d)},Yhb=function(a,b,c){a.j||(a.j=new e4);
a=a.j.kp(b,c);Math.random()<.01&&g.qx(Error("Deprecated subtitles format in web player: WebVTT"));return a},$hb=function(a,b,c,d){if(c[0]==="{")try{return a.j||(a.j=new W3(Zhb(b))),a.j.kp(c,d)}catch(f){return g.px(f),[]}var e=g.n1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if(e.firstChild.tagName==="timedtext"){if(Number(e.firstChild.getAttribute("format"))===3)return a.j||(a.j=new Q3(Zhb(b),a.Y)),a.j.kp(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if(e.firstChild.tagName==="transcript")throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},Zhb=function(a){var b=
{};
if(a=g.AQ(a))b.lang=a,g.Pbb.test(a)&&(b.Xi=1);return b},g4=function(a){g.hY.call(this,a);
var b=this;this.J=a;this.Fa=[];this.Aa={};this.Ua={};this.N=!1;this.B=this.j=this.Z=this.W=this.Oa=this.qb=null;this.Y=this.J.U();this.videoData=this.J.getVideoData();this.sb=this.J.ob();var c;this.eb=(c=this.J.getVideoData(1))==null?void 0:g.oR(c);this.C={Ve:{}};this.G={Ve:{}};this.Rb=g.TR(this.videoData);this.Ya=g.H0a(this.videoData,this.J);this.Hb=!!this.videoData.captionTracks.length;this.Ub=!!this.videoData.Ee;this.Ta=this.Y.controlsType==="3";this.Wa=new f4(this.J,this.Y);this.oa=new g.kG(this);
this.K=new g.S({I:"div",S:"ytp-caption-window-container",X:{id:"ytp-caption-window-container"}});this.qa={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.oq("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.fq(d));this.storage=c;var e;this.Ib=!((e=a.Ge())==null||!e.yI());this.D=aib(this);this.Ca=!this.D&&this.Ta&&this.Ib&&this.Ya;g.P(this,this.Wa);this.D?this.Ia=this.Ka=null:(this.Ka=new g.Dp(this.fV,void 0,this),g.P(this,this.Ka),this.Ia=new g.Ep(this.mea,2E3,this),g.P(this,
this.Ia));g.P(this,this.oa);g.vS(this.player,this.K.element,4);g.P(this,this.K);this.oa.T(a,"contentPoTokenReady",this.fH);this.D||this.oa.T(a,"resize",this.hV);(this.Eb=g.RP(this.Y)&&!g.Ws()&&!this.J.isFullscreen()&&!this.D&&!this.Ca)&&this.oa.T(a,"resize",this.Mba);this.oa.T(a,"onPlaybackAudioChange",this.Yaa);this.oa.T(a,g.ME("captions"),function(f){b.onCueRangeEnter(f)});
this.oa.T(a,g.NE("captions"),function(f){b.onCueRangeExit(f)});
this.eb&&this.oa.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
bib(this,Cgb()||{});this.player.Ed("onCaptionsModuleAvailable")},eib=function(a){if(a.Y.Ib===1||a.videoData.DD===1||g.CR(a.videoData,"yt:cc")==="alwayson")return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(a.Y.Ib===2){if(g.gQ(a.Y))var c=cib(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(c!=null)return!!c}c=tgb(a.player.getAudioTrack(),g.gQ(a.Y));var d=g.CR(a.videoData,"yt:cc");if(dib(a)===void 0){if(c==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return d?d==="on":!0;if(c==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return d==="on"}else return d==="on";return b==="ON"||g.CR(a.videoData,
"yt:cc")==="on"},h4=function(a,b){if(a.B&&(b===void 0||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||a.B==="FORCED_ON"},dib=function(a){var b=void 0,c=g.ut(g.tt(),65);
if(g.gQ(a.Y)&&c!=null){if(cib(a)!=null)return!1;b=!c}return b},fib=function(a){var b;
a.Rb?b=new Y3(a.Y,a.videoData,a.getAudioTrack(),a.player):a.Ya?b=new C3(a.videoData.j,a.player):a.Hb?b=new g.lY(a.Y,a.videoData,a.getAudioTrack()):b=new g.mY(a.Y,a.videoData.Ee,a.videoData.videoId,g.zMa(a.videoData),a.videoData.Un,a.videoData.eventId);return b},j4=function(a,b){if(a.j){if(a.Z&&a.Z.D)return a.Z.D;
g.OR(a.videoData)&&(b=!0);b||(b=a.Ub?!1:a.Hb?!1:!0);b=b||gib(a);b=g.iY(a.j.B,b);var c=null;if(ugb(a.Y)){var d=a.J.isInline()?void 0:g.mt("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.CR(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.AQ(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.AQ(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.G,
e.length))for(e=g.w(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.CR(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.AQ(b[f])===d[e])return b[f];d=null;a.Z&&a.Z.C&&(d=a.Z.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||i4(a));d&&c&&g.AQ(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=vgb(d,c));return d}return null},i4=function(a){return a.Z&&a.Z.j},k4=function(a){var b=i4(a);
return!!b&&a.B===b},hib=function(a){var b=tgb(a.player.getAudioTrack(),g.gQ(a.Y)),c;
b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?c=j4(a,a.N):b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&h4(a)?c=i4(a):dib(a)||a.N||eib(a)?c=j4(a,a.N):h4(a)&&(c=i4(a));if(a.D||a.Ca){var d=g.iY(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.qh("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.yQ(f));h.setAttribute("srclang",g.AQ(f));h.setAttribute("id",f.toString());a.Ca||h.setAttribute("src",a.j.Nx(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.Ge();c.NE(b);c=
c.Kb();a.Ib&&a.oa.T(c.textTracks,"change",a.lda)}else!a.B&&c&&l4(a,c),a.player.Ed("onCaptionsTrackListChanged"),a.player.uf("onApiChange")},iib=function(a,b){var c=a.J.Ge().Kb().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?e.mode!=="showing"&&(e.mode="showing"):e.mode==="showing"&&(e.mode="disabled"))}},l4=function(a,b,c){a.loaded&&a.unload();
c!=null&&(a.N=c,a.N&&(g.gQ(a.Y)?m4(a,!!b):n4(a,!!b)));a.Y.L("html5_report_caption_format_change")&&jib(a,a.B,b,a.N,!1);a.B=b;h4(a)&&(b=i4(a),a.Y.L("html5_report_caption_format_change")&&jib(a,a.B,b,a.N,!0),a.B=b);var d;kib(a,(d=a.B)!=null?d:void 0);a.load()},mib=function(a,b){if(b instanceof O3){var c=a.Aa[b.id];
c&&c.B!==b&&(c.dispose(),delete a.Aa[b.id],c=null);c||(c=lib(a,b))&&(a.Aa[b.id]=c)}else c=b.windowId,a.Ua[c]||(a.Ua[c]=[]),a.Ua[c].push(b)},lib=function(a,b){var c=nib(a);
if(!c)return null;var d=a.B?g.AQ(a.B):null;d&&g.Pbb.test(d)&&(b.params.Xi=1);var e=a.sb.getPlayerSize();d=e.height*a.qa.height;e=e.width*a.qa.width;a.Y.playerStyle!=="google-live"||a.C.isDefault||Object.assign(b.params,a.C);switch(b.params.PB!=null?b.params.PB:b.j.length>1?1:0){case 1:return new Z3(b,a.C,a.G,c.width,c.height,e,d,a.Y.experiments,a.ZN.bind(a),a.J);case 2:return new d4(b,a.C,a.G,c.width,c.height,e,d,a.Y.experiments,a.ZN.bind(a),a.J);default:return new D3(b,a.C,a.G,c.width,c.height,e,
d,a.Y.experiments,a.ZN.bind(a),a.J)}},bib=function(a,b,c){c=c===void 0?!1:c;
var d=o4.Ve;a.C={};Object.assign(a.C,o4);a.C.Ve={};Object.assign(a.C.Ve,d);a.G={Ve:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;U3.test(f);e.Ve.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;U3.test(f);e.Ve.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||o4.windowColor;U3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;f==null&&(f=d.backgroundOpacity);e.Ve.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
f==null&&(f=d.fontSizeIncrement);e.Ve.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;e==null&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Ve;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;f==null&&(f=d.textOpacity);e.Ve.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;f==null&&(f=o4.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;f==null&&(f=d.charEdgeStyle);e.Ve.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;f==null&&(f=d.fontFamily);e.Ve.fontFamily=f;a.loaded&&a.hV();c&&g.lt("yt-player-caption-display-settings",b,2592E3)},pib=function(a,b,c){b&&!a.W?(b=Hhb({Xi:0,
lang:"ko"}),a.W=[b,new M3(b.start,b.end-b.start,0,b.id,c!=null?c:"\uc790\ub9c9\uc740 \uc774\ub807\uac8c \ud45c\uc2dc\ub429\ub2c8\ub2e4.")],a.player.qf(a.W)):!b&&a.W&&(oib(a,a.W),a.W=null)},oib=function(a,b){a.player.xp(b);
b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.Yb(a.Fa,c.value);A3(a.Ka)},kib=function(a,b){a.Y.L("html5_modify_caption_vss_logging")&&(a.videoData.yE=b)},nib=function(a){var b=a.sb.getVideoContentRect(!0).height,c=a.sb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.qa.height;c*=a.qa.width;return{width:c,height:b}},n4=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},m4=function(a,b){a.J.isInline()||g.lt("yt-player-sticky-caption",b,2592E3)},cib=function(a){if(!a.J.isInline())return g.mt("yt-player-sticky-caption")},aib=function(a){var b,c=!((b=a.J.Ge())==null||!b.xI());
return a.Ta&&c&&!a.Ya},gib=function(a){return a.Y.L("web_deprecate_always_includes_asr_setting")&&g.gQ(a.Y)?!0:!!g.ut(g.tt(),66)},jib=function(a,b,c,d,e){e?a.tj(c,!0,"g"):d?b?a.tj(c,!!c,"m"):c&&a.tj(c,!0,"m"):!b&&c&&a.tj(c,!0,"s")};
g.kY.prototype.CT=g.da(55,function(){return!1});
g.kY.prototype.Zu=g.da(54,function(){});
g.lY.prototype.Zu=g.da(53,function(a,b,c){var d=this;this.Ja();b=this.Nx(a,b);var e=this.Y.L("html5_report_captions_ctmp_qoe"),f=(0,g.hu)();this.Ct();sgb(this,b,{format:"RAW",onSuccess:function(h){d.j=null;if(e){var l=(h.responseText.length/1024).toFixed(),m=(0,g.hu)();d.videoData.ma("capresp",{ms:m-f,kb:l})}c(h.responseText,a)},
onError:e?function(h){var l;h=(l=h==null?void 0:h.status)!=null?l:0;d.videoData.ma("capfail",{status:h})}:void 0,
withCredentials:!0})});
g.mY.prototype.Zu=g.da(52,function(a,b,c){var d=this;this.Ja();b=this.Nx(a,b);this.Ct();this.j=g.ds(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.TX.prototype.sA=g.da(51,function(){for(var a=g.ih(document,"track",void 0,this.j),b=0;b<a.length;b++)g.vh(a[b])});
g.o_.prototype.sA=g.da(50,function(){this.mediaElement.sA()});
g.TX.prototype.yI=g.da(49,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.o_.prototype.yI=g.da(48,function(){return this.mediaElement.yI()});
g.TX.prototype.xI=g.da(47,function(){return!!this.j.textTracks});
g.o_.prototype.xI=g.da(46,function(){return this.mediaElement.xI()});
g.TX.prototype.NE=g.da(45,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.o_.prototype.NE=g.da(44,function(a){this.mediaElement.NE(a)});
g.TV.prototype.JI=g.da(40,function(a,b,c){this.bd.JI(a,b,c)});
g.x_.prototype.JI=g.da(39,function(a,b,c){this.Ka.set(a,{fu:b,eA:c})});
g.TV.prototype.QF=g.da(38,function(a){return this.bd.QF(a)});
g.x_.prototype.QF=g.da(37,function(a){var b=2;this.K.has(a)?b=0:g.p6a(this,a)&&(b=1);return b});
g.PT.prototype.j=g.da(36,function(a){g.UOa.apply(null,[6,this.tag,a].concat(g.x(g.Ea.apply(1,arguments))))});
g.oS.prototype.al=g.da(34,function(a,b){var c=g.iS(this.app);c&&c.al(a,b)});
g.kW.prototype.al=g.da(33,function(a,b){a=[a,b];g.jW(this,g.RK(this.provider),"cfi",a)});
g.yW.prototype.al=g.da(32,function(a,b){this.qoe&&this.qoe.al(a,b)});
g.ZW.prototype.al=g.da(31,function(a,b){this.Tb().al(a,b)});
g.oS.prototype.tj=g.da(30,function(a,b,c){var d=g.iS(this.app);d&&d.tj(a,b,c)});
g.kW.prototype.tj=g.da(29,function(a,b,c){b=[a,b,this.Ub,c];g.jW(this,g.RK(this.provider),"cfs",b);this.Ub=a});
g.yW.prototype.tj=g.da(28,function(a,b,c){this.qoe&&this.qoe.tj(a,b,c)});
g.ZW.prototype.tj=g.da(27,function(a,b,c){this.Tb().tj(a,b,c)});
g.OV.prototype.eG=g.da(18,function(){return this.N});
g.V_.prototype.eG=g.da(17,function(){var a;return((a=g.iS(this))==null?void 0:a.UA())||null});
g.oS.prototype.UA=g.da(16,function(){return this.app.eG()});
g.ZW.prototype.UA=g.da(15,function(){var a;return((a=this.ra)==null?void 0:a.eG())||null});
g.HM.prototype.PK=g.da(1,function(a){return(a=this.Co(a))?a.j:0});
g.gO.prototype.PK=g.da(0,function(){return 0});
var zgb=/#(.)(.)(.)/,ygb=/^#(?:[0-9a-f]{3}){1,2}$/i,Hgb={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",
la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",
mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",
naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",
or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",
ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",
shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",
sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",
tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",
xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
B3.prototype.contains=function(a){a=g.fc(this.segments,a);return a>=0||a<0&&(-a-1)%2===1};
B3.prototype.length=function(){return this.segments.length/2};
g.z(Egb,g.O);g.k=Egb.prototype;g.k.xa=function(){g.O.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.aC=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Bc();var b=this.j;this.j=g.Rb(this.oa.Zr(a).ib);b!==this.j&&this.W&&this.W()};
g.k.reset=function(){this.D=new B3;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.K_=function(){this.Ja();var a;if(a=this.j!=null)a=this.j,a=a.j.Nt(a);if(a&&!this.C&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){a=this.j;a=a.j.TD(a);var b=a.ib[0],c;if((c=this.player.getVideoData())==null?0:c.enableServerStitchedDai)if(c=this.player.UA()){var d=b.j.info.id,e=b.Ma,f=a.ib[0].Me;if(this.policy.Oa){if(c=c.SK(f,e,d,3))a.D=c}else if(d=c.MA(f,e,d,3))if(c=c.QF(e),c===0)d&&(a.j=new g.zM(d));else if(c===2){this.N.start();Fgb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.No(b.Ma)?(this.D.contains(a.ib[0].Ma)||Ggb(this,a),this.j=g.Rb(a.ib)):Fgb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.z(C3,g.kY);g.k=C3.prototype;g.k.Zu=function(a,b,c){var d=this;this.Ct();b=Jgb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?Kgb(this,b,"386"):Kgb(this,b));if(b){var e=(b.index.PK(b.index.Fo())-b.index.getStartTime(b.index.Fo()))*1E3,f=new g.cSa(this.Y),h=function(){d.C&&d.C.reset();d.K=!0};
this.Y.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new Egb(f,this.J,b,function(l,m){c(l,a,m,e)},this.N||g.yG(b.info),h)}};
g.k.CT=function(){var a=this.K;this.K=!1;return a};
g.k.EB=function(a){var b=this.N?[new g.xQ({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.xQ({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?Igb(this,"386"):Igb(this);b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.jY(this.B,c.value);a()};
g.k.Ct=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Nx=function(){return""};
g.k.PH=function(){this.C&&(this.C.reset(),this.J.lf("captions"))};
var U3=/^#(?:[0-9a-f]{3}){1,2}$/i;var fhb=["left","right","center","justify"];g.z(D3,g.S);g.k=D3.prototype;g.k.l5=function(a,b){this.Ya=a;this.eb=b;var c=g.Pm(this.element,this.element.parentElement);this.qb=a-c.x;this.sb=b-c.y};
g.k.k5=function(a,b){if(a!==this.Ya||b!==this.eb){g.Lp(this.element,"ytp-dragging")||g.Mp(this.element,"ytp-dragging");var c=g.Rm(this.element);a=a-this.qb-.02*this.playerWidth;var d=b-this.sb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Bg(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.Bg(f,0,2));b=e+f*3;a=(a+e/2*c.width)/this.maxWidth;a=g.Bg(a,0,1)*100;c=(d+f/2*c.height)/this.maxHeight;c=g.Bg(c,0,1)*100;this.B.params.Rm=b;this.B.params.Fp=c;this.B.params.Pk=
a;this.B.params.isDefault=!1;this.j.Rm=b;this.j.Fp=c;this.j.Pk=a;this.j.isDefault=!1;this.qa.Rm=b;this.qa.Fp=c;this.qa.Pk=a;this.qa.isDefault=!1;this.q2()}};
g.k.j5=function(){g.Op(this.element,"ytp-dragging")};
g.k.q2=function(){this.TC(this.K)};
g.k.getType=function(){return this.type};
g.k.TC=function(a){var b=this.Eb?0:Math.min(this.aZ(),this.maxWidth),c=this.ZY(),d=this.Eb;if(d){var e=getComputedStyle(this.D.parentNode);e=E3(e.borderLeftWidth)+E3(e.borderRightWidth)+E3(e.paddingLeft)+E3(e.paddingRight)}else e=0;var f=e;e="";this.B.params.Xi===3&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.Fm(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.VO(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=this.j.Pk*.96+2;h=this.j.Rm;switch(h){case 0:case 3:case 6:(d=this.j.Ve.fontSizeIncrement)&&d>0&&this.j.Xi!==2&&this.j.Xi!==3&&(l=Math.max(l/(1+d*2),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=this.j.Fp*.96+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.Fm(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],typeof e.text==="string"&&(d+=e.text.split("\n").length-1,e.append||b===0||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.VO=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Fa||this.K.length>b)b=0,this.Fa=!1,this.K=[],this.N=this.Ia=this.Ka=null,g.th(this.D);for(;b<a.length;b++)khb(this,a[b])};
g.k.aZ=function(){return 0};
g.k.ZY=function(){return 0};
g.k.toString=function(){return g.S.prototype.toString.call(this)};mhb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
mhb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var nhb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];F3.prototype.set=function(a){this.type=a};
F3.prototype.get=function(){return this.type};
G3.prototype.clear=function(){this.state=0};
G3.prototype.update=function(){this.state=this.state===2?1:0};
G3.prototype.ze=function(){return this.state!==0};
G3.prototype.matches=function(a,b){return this.ze()&&a===this.hx&&b===this.Ut};
shb.prototype.reset=function(){this.timestamp=this.j=0};
H3.prototype.updateTime=function(a){for(var b=1;b<=15;++b)for(var c=1;c<=32;++c)this.B[b][c].timestamp=a};
H3.prototype.debugString=function(){for(var a="\n",b=1;b<=15;++b){for(var c=1;c<=32;++c){var d=this.B[b][c];a=d.j===0?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
H3.prototype.reset=function(a){for(var b=0;b<=15;b++)for(var c=0;c<=32;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var thb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],uhb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],vhb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],whb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Ahb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
lhb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};Ehb.prototype.D=function(){};g.z(M3,g.KE);M3.prototype.toString=function(){return g.KE.prototype.toString.call(this)};g.z(N3,g.O);N3.prototype.kp=function(){return[]};
N3.prototype.reset=function(){};g.z(O3,g.KE);O3.prototype.toString=function(){return g.KE.prototype.toString.call(this)};
var P3=0;g.z(Q3,N3);Q3.prototype.reset=function(){this.K={};this.B=this.j=null;this.G=!0};
Q3.prototype.kp=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.w(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,c.nodeType===1)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.w(d),a=d.next();!a.done;a=d.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=S3(a,"b");
l!=null&&(h.bold=l);l=S3(a,"i");l!=null&&(h.italic=l);l=S3(a,"u");l!=null&&(h.underline=l);l=T3(a,"et");l!=null&&(h.charEdgeStyle=l);l=T3(a,"of");l!=null&&(h.offset=l);l=V3(a,"bc");l!=null&&(h.background=l);l=V3(a,"ec");l!=null&&(h.mP=l);l=V3(a,"fc");l!=null&&(h.color=l);l=T3(a,"fs");l!=null&&l!==0&&(h.fontFamily=l);l=R3(a,"sz");l!==void 0&&(h.fontSizeIncrement=l/100-1);l=R3(a,"bo");l!==void 0&&(h.backgroundOpacity=l/255);l=R3(a,"fo");l!==void 0&&(h.textOpacity=l/255);l=T3(a,"rb");l!=null&&l!==10&&
l!==0&&(h.jg=l>10?l-1:l);a=T3(a,"hg");a!=null&&(h.TZ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=Ihb(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=Jhb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.w(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "w":this.j=Khb(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!S3(m,"a");l=(R3(m,"t")||0)+l;var n=R3(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&this.B.text==="\n"&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=m.getAttribute("d")!=null);for(m=0;m<r.length;m++){var t=r[m],u=void 0;m>0&&(h=!0);var y=void 0;t.nodeType===1&&(y=t);if(y&&y.tagName==="s"){if((t=(t=y.getAttribute("p"))?this.pens[t]:null)&&t.jg&&(t.jg===1?(t=r.slice(m,
m+4),t.length===4&&(u=Ghb(l,n,f,h,p,t,this.pens),m+=3)):u=Ghb(l,n,f,h,p,[y],this.pens)),!u){var A=y;u=l;y=n;t=f;var C=h,F=p,H=A.textContent?A.textContent:"",L=A.getAttribute("p");L=L?this.pens[L]:null;A=R3(A,"t")||0;u=new M3(u+A,y-A,F,t,H,C,L)}}else u=new M3(l,n,p,f,t.textContent||"",h,q);c.push(u);this.B=u}if(c.length>0)for(c[0].windowId===this.D&&(this.j=Khb(this,a,b,!0),d.push(this.j)),a=g.w(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var qib=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.z(W3,N3);W3.prototype.reset=function(){this.B.clear()};
W3.prototype.kp=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.w(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;h!=null&&(f.offset=h);e.szPenSize!==void 0&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;h!=null&&(f.charEdgeStyle=h);e.ecEdgeColor!==void 0&&(f.mP=X3(e.ecEdgeColor));h=e.fsFontStyle;h!=null&&h!==0&&(f.fontFamily=
h);e.fcForeColor!==void 0&&(f.color=X3(e.fcForeColor));e.foForeAlpha!==void 0&&(f.textOpacity=e.foForeAlpha/255);e.bcBackColor!==void 0&&(f.background=X3(e.bcBackColor));e.boBackAlpha!==void 0&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&h!==10&&(f.jg=h>10?h-1:h,f.Cp=qib.get(f.jg));e.hgHorizGroup&&(f.TZ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.w(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),e.mhModeHint!==void 0&&(f.PB=e.mhModeHint),e.juJustifCode!==void 0&&(f.textAlign=e.juJustifCode),e.pdPrintDir!==void 0&&(f.Xi=e.pdPrintDir),e.sdScrollDir!==void 0&&(f.TU=e.sdScrollDir),e.wfcWinFillColor!==void 0&&(f.windowColor=X3(e.wfcWinFillColor)),e.wfoWinFillAlpha!==void 0&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.w(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),e.ahHorPos!==
void 0&&(f.Pk=e.ahHorPos),e.apPoint!==void 0&&(f.Rm=e.apPoint),e.avVerPos!==void 0&&(f.Fp=e.avVerPos),e.ccCols!==void 0&&(f.Xt=e.ccCols),e.rcRows!==void 0&&(f.Us=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.w(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=Lhb(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+P3++,d=Lhb(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;f===0&&(f=5E3);
l=this.B.get(h);var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],u=t.utf8;if(u){var y=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if((l.params.PB!=null?l.params.PB:l.j.length>1?1:0)===2&&n&&u==="\n")continue;t=null;var C=[],F;if(F=A&&A.jg===1){F=q;var H=m;if(H+3>=F.length||!F[H+1].pPenId||!F[H+2].pPenId||!F[H+3].pPenId)F=!1;else{var L=F[H+1].pPenId;(L=this.j.get(L))&&L.jg&&L.jg===2?(L=F[H+2].pPenId,L=this.j.get(L),!L||!L.jg||
L.jg<3?F=!1:(L=F[H+3].pPenId,F=(L=this.j.get(L))&&L.jg&&L.jg===2?!0:!1)):F=!1}}if(F)y=q[m+1].utf8,t=q[m+3].utf8,F=q[m+2].utf8,H=this.j.get(q[m+2].pPenId),u=Fhb(u,y,F,t,H),t=new M3(e,f,p,h,u,n,A),m+=3;else{if(u.indexOf("<")>-1){var N=void 0;C=A;F=r;H=e;L=f;var Y=y,V=p,ca=n,ma=[],W=g.n1("<html>"+u+"</html>");if(!W.getElementsByTagName("parsererror").length&&((N=W.firstChild)==null?0:N.childNodes.length))for(N=g.w(W.firstChild.childNodes),W=N.next();!W.done;W=N.next()){W=W.value;var R=void 0,X=void 0,
v=(X=(R=W.textContent)==null?void 0:R.replace(/\n/g,""))!=null?X:"";if(W.nodeType!==3||v&&v.match(/^ *$/)==null){R={};Object.assign(R,C||F);X=void 0;switch((X=W)==null?void 0:X.tagName){case "b":R.bold=!0;break;case "i":R.italic=!0;break;case "u":R.underline=!0}ma.push(new M3(H+Y,L-Y,V,l.id,v,ca,R))}}C=ma}C.length||(C=[new M3(e+y,f-y,p,l.id,u,n,A||r)])}if(C.length)for(n=g.w(C),A=n.next();!A.done;A=n.next())A=A.value,d.push(A),l.j.push(A);else t&&(d.push(t),l.j.push(t))}n=!0}}}b=a}else b=[];return b};g.z(Y3,g.kY);Y3.prototype.Zu=function(a,b,c){xgb(this.videoData.videoId,a.vssId,c)};
Y3.prototype.EB=function(a){if(this.audioTrack)for(var b=g.w(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.jY(this.B,c.value);a()};g.z(Z3,D3);Z3.prototype.VO=function(a){var b=this.B.j;D3.prototype.VO.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,rib);var e=c.j;var f=d}khb(this,c,d)}};
var rib={C$:!0};g.z($3,Ehb);$3.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+P3++;c=c/1E3-this.K;d=d/1E3-this.K;a=new O3(c,d-c,5,f,{textAlign:0,Rm:0,Pk:b*2.5,Fp:a*5.33});e=new M3(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.z(c4,N3);c4.prototype.kp=function(a){a=new $3(a,a.byteLength,this.B);if(Mhb(a)){for(;a.byteOffset<a.j.byteLength;)for(a.version===0?a.C=b4(a)*(1E3/45):a.version===1&&(a.C=b4(a)*4294967296+b4(a)),a.G=a4(a);a.G>0;a.G--){var b=a4(a),c=a4(a),d=a4(a);b&4&&(b&3)===this.track&&(this.track===0||this.track===1)&&(b=this.j,b.j.push({time:a.C,type:this.track,YX:c,ZX:d,order:b.j.length}))}rhb(this.j,a);return a.B}return[]};
c4.prototype.reset=function(){this.j.clear()};g.z(d4,D3);g.k=d4.prototype;g.k.q2=function(){g.Gp(this.Ta)};
g.k.Dca=function(){g.Op(this.element,"ytp-rollup-mode");this.TC(this.Ub,!0)};
g.k.ZY=function(){return this.C?this.oa:this.W};
g.k.aZ=function(){return this.C?this.W:this.oa};
g.k.TC=function(a,b){this.Ub=a;if(this.B.params.Us){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;c>0&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Hb=this.oa;this.W=this.oa=0;D3.prototype.TC.call(this,a);Qhb(this,b)}D3.prototype.TC.call(this,a)};g.z(e4,N3);
e4.prototype.kp=function(a,b){var c=[];a=a.split(sib);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(e!==""&&!tib.test(e)){var h=uib.exec(e);if(h&&h.length>=4){var l=Shb(h[1]),m=Shb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.w(n);for(var u=n.next();!u.done;u=n.next())if(u=u.value.split(":"),u.length===2){var y=u[1];switch(u[0]){case "line":u=y.split(",");u[0].endsWith("%")&&(p=u[0],h.Fp=Number.parseInt(p,10),u.length===2&&(q=u[1].trim()));break;case "position":u=
y.split(",");r=u[0];h.Pk=Number.parseInt(r,10);u.length===2&&(t=u[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Pk=0;break;case 1:h.Pk=100;break;case 2:h.Pk=50}if(h.textAlign!=null){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=p<0||p>8?7:p;h.Rm=q}e=e.substring(uib.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(h.indexOf("<")<0&&h.indexOf("&")<0)f=Thb(l,m,5,t),m=new M3(l,m,5,f.id,h,!1,g.Sg(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(vib),q.length===1?(h=5,t=Thb(l,m,h,t)):(p=h=6,t=Object.assign({Xt:32},t),t=new O3(l,m,p,"_"+P3++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],r%2===0?(u=g.n1("<html>"+n+"</html>"),u.getElementsByTagName("parsererror").length?
(y=u.createElement("span"),y.appendChild(u.createTextNode(n))):y=u.firstChild,Rhb(this,p,m-(p-l),h,t,r>0,y,e,c)):p=Shb(n)+f}uib.lastIndex=0}}return c};
var tib=/^NOTE/,sib=/(?:\r\n|\r|\n){2,}/,uib=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),vib=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.p_.nL(e4,{kp:"wvppt"});g.z(f4,g.O);
f4.prototype.kp=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a||this.Y.L("html5_use_subfragcaps_parser_for_all_live")){a:{var e=d,f=Whb(this,a,c),h=[];try{for(var l=g.w(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.NU;h=typeof p!=="string"?h.concat(Xhb(this,b,p,q,e)):p.substring(0,6)==="WEBVTT"?h.concat(Yhb(this,p,q)):h.concat($hb(this,b,p,q))}var r=h;break a}catch(u){this.logger.j(187101178,"SS caps parsing failure fallback: "+u.message+". ");this.clear();r=null;break a}r=void 0}if(r!==
null&&r.length!==0)return r;if(this.Y.L("html5_disable_subfragcaps_fallback"))return[];r===null?(r=this.logger,g.XOa(r.tag,5,"SS caps fallback due to parse failure.",r.B)):this.logger.info("SS caps fallback due to no data received.")}if(a=Uhb(a))try{var t=typeof a!=="string"?Xhb(this,b,a,c,d):a.substring(0,6)==="WEBVTT"?Yhb(this,a,c):$hb(this,b,a,c)}catch(u){this.clear(),t=[]}else t=[];return t};
f4.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
f4.prototype.reset=function(){this.j&&this.j.reset()};
f4.prototype.xa=function(){g.O.prototype.xa.call(this);this.clear()};var o4={windowColor:"#080808",windowOpacity:0,textAlign:2,Rm:7,Pk:50,Fp:100,isDefault:!0,Ve:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.z(g4,g.hY);g.k=g4.prototype;g.k.xa=function(){if(this.D||this.Ca){var a=this.J.Ge();a&&!a.Ja()&&a.sA()}else pib(this,!1);g.hY.prototype.xa.call(this)};
g.k.zU=function(){return this.Y.L("html5_honor_caption_availabilities_in_audio_track")&&!this.Ya};
g.k.Sv=function(){if(this.Ta)return this.D||this.Ca;var a=this.getAudioTrack();if(this.zU()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=tgb(a,g.gQ(this.Y));return a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?h4(this):dib(this)||h4(this)?!0:eib(this)};
g.k.load=function(){var a=this;g.hY.prototype.load.call(this);this.Z=this.getAudioTrack();this.j?this.B&&(this.Wa.clear(),this.D?iib(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.Zu(this.B,"json3",function(b,c,d,e){if(b){var f;kib(a,(f=a.B)!=null?f:void 0);a.j.CT()&&(a.Fa=[],a.J.lf("captions"),A3(a.Ka),a.Wa.reset());if(a.videoData.Hd){var h;d=((h=d)!=null?h:0)+a.videoData.Hd}b=a.Wa.kp(b,c,d,e);if(a.eb)for(c=g.w(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.im=a.videoData.Hd;c=!a.Y.L("html5_keep_caption_data_after_seek")&&a.Ya;a.player.qf(b,void 0,c);!a.N||a.Ca||k4(a)||!a.Y.Lm||g.hE(a.Y)||g.TP(a.Y)||g.vz(a.Y)||a.Y.Ka==="shortspage"||a.player.isInline()||(g.Hp(a.Ia),b=Hhb({Rm:0,Pk:5,Fp:5,Us:2,textAlign:0,Xi:0,lang:"ko"}),a.Oa=[b],c=["\uc124\uc815\uc744 \ud655\uc778\ud558\ub824\uba74 ","\uc744 \ud074\ub9ad\ud558\uc138\uc694."],a.qb||(e=new g.Ux(g.my()),g.P(a,e),a.qb=e.element),e=b.end-b.start,(f=g.yQ(a.B))&&a.Oa.push(new M3(b.start,e,0,b.id,f)),a.Oa.push(new M3(b.start,
e,0,b.id,c[0]),new M3(b.start,e,0,b.id,a.qb,!0),new M3(b.start,e,0,b.id,c[1],!0)),a.player.qf(a.Oa),g.Fp(a.Ia));!a.N||a.Ca||k4(a)||(g.gQ(a.Y)?m4(a,!0):n4(a,!0),a.Z&&(a.Z.D=a.B),a.player.Jp());a.N=!1}}),this.D||this.Ca||k4(this)||this.player.Ed("captionschanged",g.zQ(this.B))):(this.j=fib(this),g.P(this,this.j),this.j.EB(function(){hib(a)}))};
g.k.unload=function(){this.D&&this.B?iib(this,!1):(this.Ia&&g.Hp(this.Ia),this.player.lf("captions"),this.Fa=[],this.j&&this.j.Ct(),this.Wa.clear(),this.W&&this.player.qf(this.W),this.hV());g.hY.prototype.unload.call(this);this.player.Jp();this.player.Ed("captionschanged",{})};
g.k.create=function(){this.Sv()&&this.load();var a;a:{var b,c,d;if(this.Y.L("web_player_nitrate_promo_tooltip")&&((b=this.videoData.getPlayerResponse())==null?0:(c=b.captions)==null?0:(d=c.playerCaptionsTracklistRenderer)==null?0:d.enableTouchCaptionsNitrate)){var e,f;if(b=(a=this.videoData.getPlayerResponse())==null?void 0:(e=a.captions)==null?void 0:(f=e.playerCaptionsTracklistRenderer)==null?void 0:f.captionTracks)for(a=g.w(b),e=a.next();!e.done;e=a.next())if(e=e.value,e.kind==="asr"&&e.languageCode===
"en"){a=!0;break a}}a=!1}a&&this.J.publish("showpromotooltip",this.K.element)};
g.k.lda=function(){for(var a=this.J.Ge().Kb().textTracks,b=null,c=0;c<a.length;c++)if(a[c].mode==="showing")a:{b=g.iY(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&l4(this,b,!0)};
g.k.Ofa=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Fa.push(a);A3(this.Ka)};
g.k.onCueRangeExit=function(a){g.Yb(this.Fa,a);this.j instanceof C3&&this.j.N&&this.player.xp([a]);A3(this.Ka)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.mea=function(){oib(this,this.Oa);this.Oa=null};
g.k.fV=function(){var a=this;if(!this.Eb||!this.D){this.Ka.stop();g.pea(this.Ua);this.Fa.sort(g.LE);var b=this.Fa;if(this.W){var c=g.Bn(b,function(f){return this.W.indexOf(f)===-1},this);
c.length&&(b=c)}b=g.w(b);for(c=b.next();!c.done;c=b.next())mib(this,c.value);b=g.w(Object.entries(this.Aa));var d=b.next();for(c={};!d.done;c={hB:void 0,cq:void 0},d=b.next()){var e=g.w(d.value);d=e.next().value;e=e.next().value;c.hB=d;c.cq=e;this.Ua[c.hB]?(c.cq.element.parentNode||(c.cq instanceof d4||c.cq instanceof Z3||g.Lg(this.Aa,function(f){return function(h,l){l!==f.hB&&h.B.params.Rm===f.cq.B.params.Rm&&h.B.params.Pk===f.cq.B.params.Pk&&h.B.params.Fp===f.cq.B.params.Fp&&(h.dispose(),delete a.Aa[l]);
return l===f.hB}}(c),this),this.K.element.appendChild(c.cq.element)),c.cq.TC(this.Ua[c.hB])):(c.cq.dispose(),delete this.Aa[c.hB])}}};
g.k.sea=function(){bib(this,{},!0);this.player.Ed("captionssettingschanged")};
g.k.O9=function(){var a=o4.Ve;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:o4.windowColor,windowOpacity:o4.windowOpacity};var b=Cgb()||{};b.background!=null&&(a.background=b.background);b.backgroundOverride!=null&&(a.backgroundOverride=b.backgroundOverride);b.backgroundOpacity!=null&&(a.backgroundOpacity=
b.backgroundOpacity);b.backgroundOpacityOverride!=null&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);b.charEdgeStyle!=null&&(a.charEdgeStyle=b.charEdgeStyle);b.charEdgeStyleOverride!=null&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);b.color!=null&&(a.color=b.color);b.colorOverride!=null&&(a.colorOverride=b.colorOverride);b.fontFamily!=null&&(a.fontFamily=b.fontFamily);b.fontFamilyOverride!=null&&(a.fontFamilyOverride=b.fontFamilyOverride);b.fontSizeIncrement!=null&&(a.fontSizeIncrement=
b.fontSizeIncrement);b.fontSizeIncrementOverride!=null&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);b.fontStyle!=null&&(a.fontStyle=b.fontStyle);b.fontStyleOverride!=null&&(a.fontStyleOverride=b.fontStyleOverride);b.textOpacity!=null&&(a.textOpacity=b.textOpacity);b.textOpacityOverride!=null&&(a.textOpacityOverride=b.textOpacityOverride);b.windowColor!=null&&(a.windowColor=b.windowColor);b.windowColorOverride!=null&&(a.windowColorOverride=b.windowColorOverride);b.windowOpacity!=null&&
(a.windowOpacity=b.windowOpacity);b.windowOpacityOverride!=null&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.Z3=function(a,b){var c={};Object.assign(c,Cgb());Object.assign(c,a);bib(this,c,b);this.player.Ed("captionssettingschanged")};
g.k.hV=function(){!this.D&&this.loaded&&(g.Ig(this.Aa,function(a,b){a.dispose();delete this.Aa[b]},this),this.fV())};
g.k.oi=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Bg(b,-2,4);this.Z3({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&l4(this,this.B,!0);break;case "stickyLoading":b!==void 0&&this.Y.N&&(g.gQ(this.Y)?m4(this,!!b):n4(this,!!b));break;case "track":if(!this.j)return{};if(b){this.Y.L("html5_report_caption_format_intent")&&!g.Sg(b)&&this.al(b.vss_id,"m");if(this.D)break;if(!g.Ta(b))break;if(g.Sg(b)){l4(this,null,!0);break}a=g.iY(this.j.B,!0);for(var d=0;d<a.length;d++){var e=
a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||(e.captionId||"")!==(b.captionId||"")||g.yQ(e)!==b.displayName)||(c=b.translationLanguage?vgb(e,b.translationLanguage):e)}this.LN(b.position);!c||c===this.B&&this.loaded||(b=g.WL(),a=g.AQ(c),b.length&&a===b[b.length-1]||(b.push(a),g.lt("yt-player-caption-language-preferences",b)),ugb(this.Y)&&!this.J.isInline()&&g.lt("yt-player-caption-sticky-language",a,2592E3),l4(this,c,!0))}else return this.loaded&&this.B&&!k4(this)?g.zQ(this.B):
{};return"";case "tracklist":return this.j?g.Ql(g.iY(this.j.B,!(!b||!b.includeAsr)),function(f){return g.zQ(f)}):[];
case "translationLanguages":return this.j?this.j.G.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||b===void 0||pib(this,!!b);break;case "sampleSubtitlesCustomized":this.D||pib(this,!!b,b);break;case "recommendedTranslationLanguages":return g.WL();case "defaultTranslationSourceTrackIndices":return this.j?this.j.Z:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.N&&a.push("stickyLoading");return a};
g.k.gs=function(){var a=this.B;if(this.J.aL("captions")){if(this.Y.L("html5_modify_caption_vss_logging")){var b;return(a=(b=this.videoData.yE)!=null?b:null)?{cc:g.xKa(a)}:{}}if(a)return b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.AQ(a)),{cc:b}}return{}};
g.k.Bfa=function(){this.isSubtitlesOn()?(g.gQ(this.Y)?m4(this,!1):n4(this,!1),kib(this),this.Y.L("html5_report_caption_format_change")?l4(this,null,!0):(this.unload(),h4(this,!0)&&l4(this,i4(this),!1))):this.B3()};
g.k.B3=function(){var a=k4(this)||!this.B?j4(this,!0):this.B;this.Y.L("html5_report_caption_format_intent")&&a&&this.al(a.vssId,"m");this.isSubtitlesOn()||l4(this,k4(this)||!this.B?j4(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!k4(this)};
g.k.fH=function(){this.j&&this.j.fH()};
g.k.Yaa=function(){var a=k4(this);h4(this,a)?l4(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.zU()&&(this.N=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Sv()&&(a?l4(this,j4(this),!1):this.load()))};
g.k.LN=function(a){a&&(this.qa={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=this.qa.top*100+"%",this.K.element.style.left=this.qa.left*100+"%",this.K.element.style.width=this.qa.width*100+"%",this.K.element.style.height=this.qa.height*100+"%",this.K.element.style.position="absolute",a=nib(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){a==="newdata"&&(this.videoData=b,this.loaded&&this.unload(),this.N=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.Ed("captionschanged",{})),this.Sv()&&this.load())};
g.k.getAudioTrack=function(){return this.eb&&this.player.getPresentingPlayerType()===2?this.videoData.rl:this.player.getAudioTrack()};
g.k.Mba=function(){var a=this.J.Ge();a&&!a.Ja()&&a.sA();this.J.isFullscreen()?(this.D=this.Ta=!0,this.loaded&&hib(this)):(this.Ta=this.Y.controlsType==="3",this.D=aib(this));l4(this,this.B)};
g.k.ZN=function(){var a,b,c,d=(a=this.videoData.getPlayerResponse())==null?void 0:(b=a.captions)==null?void 0:(c=b.playerCaptionsTracklistRenderer)==null?void 0:c.openTranscriptCommand;d&&this.player.fb("innertubeCommand",d)};
g.k.tj=function(a,b,c){var d=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,e="";a&&(e=a.vssId,e=e.replace(d,""));var f="";a&&a.getId()&&(f=a.getId()||"");a&&a.getXtags()&&(a=a.getXtags(),a=a.replace(d,""),f=f.concat(";"+a));this.J.tj(b?e:"",b?f:"",c)};
g.k.al=function(a,b){a=(a||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");this.J.al(a,b)};
g.k.PH=function(){this.j instanceof C3&&this.j.PH()};
g.p_.nL(g4,{fV:"smucd"});g.gY("captions",g4);})(_yt_player);
